apiVersion: apps/v1
kind: Deployment
metadata:
  name: $PROJECT_NAME
spec:
  template:
    spec:
      containers:
        - name: main
          image: $IMAGE
          env:
            - name: NODE_ENV
              value: "development"
              valueFrom: null
            - name: ENV
              value: "development"
              valueFrom: null
