apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: $PROJECT_NAME-workers
  namespace: default
  labels:
    app: $PROJECT_NAME-workers
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: $PROJECT_NAME-workers
  template:
    metadata:
      annotations:
        hellomd/logging.enabled: "true"
      labels:
        app: $PROJECT_NAME-workers
    spec:
      containers:
        - name: $PROJECT_NAME-workers
          image: $WORKER_IMAGE
          imagePullPolicy: Always
          resources:
            limits:
              cpu: $KUBE_LIMIT_CPU
          env:
            - name: PROJECT_NAME
              value: $PROJECT_NAME
            - name: PROJECT_RESOURCE
              value: worker
            - name: COMMIT_SHA1
              value: $COMMIT_SHA1
            - name: ENABLE_STRUCTURED_LOGGING
              value: "true"
            - name: AMQP_URL
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: amqpUrl
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: env
            - name: ENV
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: env
            - name: GATEWAY_URL
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: gatewayUrl
            - name: LOGMATIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: logmaticApiKey
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: mongoUrl
            - name: LEGACY_MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: legacyMongoUrl
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: secret
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: sentryDsn
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: awsKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: awsSecret
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: awsRegion
            - name: BLACKBIRD_URL
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: blackbirdUrl
            - name: EASYPOST_URL
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: easypostUrl
            - name: ELASTIC_URL
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: elasticUrl
            - name: ELASTIC_USER
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: elasticUser
            - name: ELASTIC_PASS
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: elasticPass
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: sendgridApiKey
            - name: SITE_URL
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: siteUrl
