apiVersion: v1
kind: Service
metadata:
  name: $PROJECT_NAME
  namespace: default
  labels:
    app: $PROJECT_NAME
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: $PROJECT_NAME
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: $PROJECT_NAME
  namespace: default
  labels:
    app: $PROJECT_NAME
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: $PROJECT_NAME
  template:
    metadata:
      annotations:
        hellomd/logging.enabled: "${ENABLE_STRUCTURED_LOGGING}"
      labels:
        app: $PROJECT_NAME
    spec:
      containers:
        - name: $PROJECT_NAME
          image: $APP_IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          # This is used when a new replica is created
          # Requests are only going to be forwarded to this probe after this amount of time
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 15
            failureThreshold: 8
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 50
            timeoutSeconds: 1
            periodSeconds: 30
          resources:
            limits:
              cpu: $KUBE_LIMIT_CPU
          env:
            - name: PROJECT_NAME
              value: $PROJECT_NAME
            - name: PROJECT_RESOURCE
              value: app
            - name: COMMIT_SHA1
              value: $COMMIT_SHA1
            - name: ENABLE_STRUCTURED_LOGGING
              value: "${ENABLE_STRUCTURED_LOGGING}"
            - name: LOGGING_LEVEL
              value: $LOGGING_LEVEL
            # Elastic APM related
            - name: ELASTIC_APM_ACTIVE
              value: "${ELASTIC_APM_ACTIVE}"
            - name: ELASTIC_APM_SERVICE_NAME
              value: $PROJECT_NAME
            - name: ELASTIC_APM_SERVICE_VERSION
              value: $COMMIT_SHA1
            - name: ELASTIC_APM_LOG_LEVEL
              value: $LOGGING_LEVEL_APM
            - name: ELASTIC_APM_TRANSACTION_SAMPLE_RATE
              value: "0.3"
            - name: ELASTIC_APM_CAPTURE_SPAN_STACK_TRACES
              value: "false"
            - name: ELASTIC_APM_API_REQUEST_TIME
              value: "20s"
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: apmToken
            - name: AMQP_URL
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: amqpUrl
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: env
            - name: ENV
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: env
            - name: GATEWAY_URL
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: gatewayUrl
            - name: LOGMATIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: logmaticApiKey
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: mongoUrl
            - name: LEGACY_MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: legacyMongoUrl
            - name: MEDICAL_MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: medicalMongoUrl
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: secret
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: sentryDsn
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: awsKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: awsSecret
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: awsRegion
            - name: BLACKBIRD_URL
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: blackbirdUrl
            - name: EASYPOST_URL
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: easypostUrl
            - name: ELASTIC_URL
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: elasticUrl
            - name: ELASTIC_USER
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: elasticUser
            - name: ELASTIC_PASS
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: elasticPass
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: sendgridApiKey
            - name: MAILGUN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: mailgunApiKey
            - name: MAILGUN_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: mailgunDomain
            - name: SITE_URL
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: siteUrl
            - name: GMAPS_GEOCODING_API_KEY
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: gmapsGeocodingApiKey
            - name: GOOGLE_CLOUD_STORAGE_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: googleCloudStorageCredentials
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: twilioAccountSid
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: twilioAuthToken
            - name: TWILIO_NUMBER
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: twilioNumber
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: encryptionKey
            - name: AUTHY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: authyApiKey
            - name: ICANPAY_SECRET
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: iCanPaySecret
            - name: ICANPAY_ID
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: iCanPayId
            - name: ICANPAY_PW
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: iCanPayPw
            - name: AUTHORIZENET_ID
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: authorizeNetId
            - name: AUTHORIZENET_TKEY
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: authorizeNetTkey
            - name: AUTHORIZENET_THC_ID
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: authorizeNetThcId
            - name: AUTHORIZENET_THC_TKEY
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: authorizeNetThcTkey
            - name: METRILO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: metriloToken
            - name: METRILO_SECRET
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: metriloSecret
            - name: ZOOMUS_KEY
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: zoomusKey
            - name: ZOOMUS_SECRET
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: zoomusSecret
