apiVersion: apps/v1
kind: Deployment
metadata:
  name: $PROJECT_NAME-workers
spec:
  template:
    spec:
      containers:
        - name: main
          resources:
            limits:
              cpu: 40m
