apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

commonLabels:
  # commented to not cause the error: The Deployment "..." is invalid: spec.selector: Invalid value: ... field is immutable
  # hellomd/kind: microservice
  app: $PROJECT_NAME

resources:
  - svc-deployment.yaml
  - svc-service.yaml
