apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

commonLabels:
  hellomd/kind: microservice
  app: $PROJECT_NAME

resources:
  - svc-deployment.yaml
  - svc-service.yaml
