apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

commonLabels:
  hellomd/kind: worker
  app: $PROJECT_NAME-workers
  parent-app: $PROJECT_NAME

resources:
  - worker-deployment.yaml
