apiVersion: apps/v1
kind: Deployment
metadata:
  name: $PROJECT_NAME-workers
spec:
  replicas: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      annotations:
        hellomd/logging.enabled: "true"
    spec:
      containers:
        - name: main
          image: $IMAGE
          imagePullPolicy: Always
          env:
            - name: PROJECT_NAME
              value: $PROJECT_NAME
            - name: PROJECT_RESOURCE
              value: worker
            - name: COMMIT_SHA1
              value: $COMMIT_SHA1
            - name: ENABLE_STRUCTURED_LOGGING
              value: "true"
            - name: LOGGING_LEVEL
              value: "info"
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: sentryDsn
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: env
            - name: ENV
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: env
            - name: GATEWAY_URL
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: gatewayUrl
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: secret
            - name: AMQP_URL
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: amqpUrl
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: mongoUrl
