apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: job-$PROJECT_NAME-$JOB_NAME
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: main
              env:
                - name: NODE_ENV
                  value: "development"
                  valueFrom: null
                - name: ENV
                  value: "development"
                  valueFrom: null
