apiVersion: apps/v1
kind: Deployment
metadata:
  name: $PROJECT_NAME
spec:
  template:
    spec:
      containers:
        - name: main
          env:
            # Overwrite some variables that are not retrieved from secrets anymore
            - name: GATEWAY_URL
              value: "http://gateway"
              valueFrom: null
            # Overwrite some variables that are not needed anymore
            - name: MAILGUN_API_KEY
              valueFrom: null
              value: "NOT_SET"
            - name: MAILGUN_DOMAIN
              valueFrom: null
              value: "NOT_SET"
            # Async stack traces on knex
            - name: HMD_KNEX_ASYNCSTACKTRACE
              value: "true"
            # Postgres
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: pgHost
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: pgPort
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: pgDatabase
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: pgUser
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: pgPassword
