apiVersion: apps/v1
kind: Deployment
metadata:
  name: $PROJECT_NAME
spec:
  template:
    metadata:
      annotations:
        hellomd/logging.enabled: "true"
    spec:
      containers:
        - name: main
          image: $IMAGE
          env:
            # Disable APM for now since monitoring is not setup on this cluster yet
            - name: ELASTIC_APM_ACTIVE
              value: "true"
            # Overwrite some variables that are not retrieved from secrets anymore
            - name: GATEWAY_URL
              value: "http://gateway"
              valueFrom: null
            # Overwrite some variables that are not needed anymore
            - name: MAILGUN_API_KEY
              valueFrom: null
              value: "NOT_SET"
            - name: MAILGUN_DOMAIN
              valueFrom: null
              value: "NOT_SET"
            # Postgres
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: pgHost
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: pgPort
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: pgDatabase
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: pgUser
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: shared-env
                  key: pgPassword
